# Generated by Django 3.1.7 on 2021-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memInfoList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('nation', models.CharField(max_length=20)),
                ('NP', models.CharField(max_length=20)),
                ('birthplace', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=4)),
                ('birthday', models.CharField(max_length=30)),
                ('health', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=6)),
                ('expText', models.CharField(max_length=1000, null=True)),
                ('writername', models.CharField(max_length=20)),
                ('writedate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_date',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
