# Generated by Django 3.1.7 on 2021-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meminfolist',
            name='id2',
            field=models.CharField(default='this a text place!', max_length=20),
        ),
    ]
