# Generated by Django 3.1.7 on 2021-05-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_App', '0003_remove_meminfolist_id2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meminfolist',
            name='writedate',
            field=models.CharField(max_length=100),
        ),
    ]
