# Generated by Django 3.1.7 on 2021-05-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_App', '0004_auto_20210505_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meminfolist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='meminfolist',
            name='writername',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
