# Generated by Django 3.1.7 on 2021-05-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_App', '0005_auto_20210505_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMECOList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ProjectNM', models.CharField(max_length=100)),
                ('ProjectCost', models.FloatField()),
                ('writername', models.CharField(max_length=20, unique=True)),
                ('writedate', models.CharField(max_length=100)),
            ],
        ),
    ]
