# Generated by Django 3.1.7 on 2021-05-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_App', '0007_auto_20210505_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMECIList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ProjectNM', models.CharField(max_length=100)),
                ('ProjectGot', models.FloatField()),
                ('writername', models.CharField(max_length=20)),
                ('writedate', models.CharField(max_length=100)),
            ],
        ),
    ]
