# Generated by Django 3.1.7 on 2021-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_App', '0008_comecilist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comecilist',
            name='ProjectClass',
            field=models.CharField(default='自研项目', max_length=50),
        ),
        migrations.AddField(
            model_name='comecolist',
            name='ProjectClass',
            field=models.CharField(default='自研项目', max_length=50),
        ),
    ]
