# Generated by Django 3.1.7 on 2021-05-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_App', '0011_auto_20210505_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ProductionNM', models.CharField(max_length=100)),
                ('ProductionUnitPrice', models.FloatField()),
                ('ProductionSoldNum', models.FloatField()),
                ('ProductionPrice', models.FloatField()),
                ('ProductionSoldDate', models.FloatField()),
            ],
        ),
    ]
