# Generated by Django 3.1.7 on 2021-05-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_App', '0012_productionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlist',
            name='ProductionSoldDate',
            field=models.CharField(max_length=100),
        ),
    ]
