# Generated by Django 3.1.7 on 2021-05-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_App', '0014_auto_20210508_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='administratorNameList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('adminname', models.CharField(max_length=20)),
                ('adminPVLevel', models.IntegerField()),
            ],
        ),
    ]
