# Generated by Django 3.2.2 on 2021-05-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_App', '0015_administratornamelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meminfolist',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
